// Top NSE F&O eligible stocks with their instrument keys
// These are used as fallback when the API instrument fetch is unavailable
export const FNO_STOCKS: { symbol: string; instrumentKey: string; name: string }[] = [
  { symbol: "RELIANCE", instrumentKey: "NSE_EQ|INE002A01018", name: "Reliance Industries" },
  { symbol: "TCS", instrumentKey: "NSE_EQ|INE467B01029", name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK", instrumentKey: "NSE_EQ|INE040A01034", name: "HDFC Bank" },
  { symbol: "INFY", instrumentKey: "NSE_EQ|INE009A01021", name: "Infosys" },
  { symbol: "ICICIBANK", instrumentKey: "NSE_EQ|INE090A01021", name: "ICICI Bank" },
  { symbol: "HINDUNILVR", instrumentKey: "NSE_EQ|INE030A01027", name: "Hindustan Unilever" },
  { symbol: "ITC", instrumentKey: "NSE_EQ|INE154A01025", name: "ITC" },
  { symbol: "SBIN", instrumentKey: "NSE_EQ|INE062A01020", name: "State Bank of India" },
  { symbol: "BHARTIARTL", instrumentKey: "NSE_EQ|INE397D01024", name: "Bharti Airtel" },
  { symbol: "KOTAKBANK", instrumentKey: "NSE_EQ|INE237A01028", name: "Kotak Mahindra Bank" },
  { symbol: "LT", instrumentKey: "NSE_EQ|INE018A01030", name: "Larsen & Toubro" },
  { symbol: "AXISBANK", instrumentKey: "NSE_EQ|INE238A01034", name: "Axis Bank" },
  { symbol: "TATAMOTORS", instrumentKey: "NSE_EQ|INE155A01022", name: "Tata Motors" },
  { symbol: "MARUTI", instrumentKey: "NSE_EQ|INE585B01010", name: "Maruti Suzuki" },
  { symbol: "SUNPHARMA", instrumentKey: "NSE_EQ|INE044A01036", name: "Sun Pharma" },
  { symbol: "TITAN", instrumentKey: "NSE_EQ|INE280A01028", name: "Titan Company" },
  { symbol: "BAJFINANCE", instrumentKey: "NSE_EQ|INE296A01024", name: "Bajaj Finance" },
  { symbol: "WIPRO", instrumentKey: "NSE_EQ|INE075A01022", name: "Wipro" },
  { symbol: "HCLTECH", instrumentKey: "NSE_EQ|INE860A01027", name: "HCL Technologies" },
  { symbol: "ASIANPAINT", instrumentKey: "NSE_EQ|INE021A01026", name: "Asian Paints" },
  { symbol: "NESTLEIND", instrumentKey: "NSE_EQ|INE239A01016", name: "Nestle India" },
  { symbol: "TATASTEEL", instrumentKey: "NSE_EQ|INE081A01020", name: "Tata Steel" },
  { symbol: "POWERGRID", instrumentKey: "NSE_EQ|INE752E01010", name: "Power Grid Corp" },
  { symbol: "NTPC", instrumentKey: "NSE_EQ|INE733E01010", name: "NTPC" },
  { symbol: "ULTRACEMCO", instrumentKey: "NSE_EQ|INE481G01011", name: "UltraTech Cement" },
  { symbol: "TECHM", instrumentKey: "NSE_EQ|INE669C01036", name: "Tech Mahindra" },
  { symbol: "ONGC", instrumentKey: "NSE_EQ|INE213A01029", name: "ONGC" },
  { symbol: "JSWSTEEL", instrumentKey: "NSE_EQ|INE019A01038", name: "JSW Steel" },
  { symbol: "M&M", instrumentKey: "NSE_EQ|INE101A01026", name: "Mahindra & Mahindra" },
  { symbol: "COALINDIA", instrumentKey: "NSE_EQ|INE522F01014", name: "Coal India" },
  { symbol: "ADANIENT", instrumentKey: "NSE_EQ|INE423A01024", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS", instrumentKey: "NSE_EQ|INE742F01042", name: "Adani Ports" },
  { symbol: "DRREDDY", instrumentKey: "NSE_EQ|INE089A01023", name: "Dr. Reddy's" },
  { symbol: "CIPLA", instrumentKey: "NSE_EQ|INE059A01026", name: "Cipla" },
  { symbol: "EICHERMOT", instrumentKey: "NSE_EQ|INE066A01021", name: "Eicher Motors" },
  { symbol: "BAJAJFINSV", instrumentKey: "NSE_EQ|INE918I01026", name: "Bajaj Finserv" },
  { symbol: "GRASIM", instrumentKey: "NSE_EQ|INE047A01021", name: "Grasim Industries" },
  { symbol: "DIVISLAB", instrumentKey: "NSE_EQ|INE361B01024", name: "Divi's Laboratories" },
  { symbol: "BPCL", instrumentKey: "NSE_EQ|INE029A01011", name: "Bharat Petroleum" },
  { symbol: "BRITANNIA", instrumentKey: "NSE_EQ|INE216A01030", name: "Britannia Industries" },
  { symbol: "APOLLOHOSP", instrumentKey: "NSE_EQ|INE437A01024", name: "Apollo Hospitals" },
  { symbol: "HEROMOTOCO", instrumentKey: "NSE_EQ|INE158A01026", name: "Hero MotoCorp" },
  { symbol: "INDUSINDBK", instrumentKey: "NSE_EQ|INE095A01012", name: "IndusInd Bank" },
  { symbol: "DABUR", instrumentKey: "NSE_EQ|INE016A01026", name: "Dabur India" },
  { symbol: "PIDILITIND", instrumentKey: "NSE_EQ|INE318A01026", name: "Pidilite Industries" },
  { symbol: "SIEMENS", instrumentKey: "NSE_EQ|INE003A01024", name: "Siemens" },
  { symbol: "HAVELLS", instrumentKey: "NSE_EQ|INE176B01034", name: "Havells India" },
  { symbol: "GODREJCP", instrumentKey: "NSE_EQ|INE102D01028", name: "Godrej Consumer" },
  { symbol: "TATACONSUM", instrumentKey: "NSE_EQ|INE192A01025", name: "Tata Consumer" },
  { symbol: "DLF", instrumentKey: "NSE_EQ|INE271C01023", name: "DLF" },
  { symbol: "SBILIFE", instrumentKey: "NSE_EQ|INE123W01016", name: "SBI Life Insurance" },
  { symbol: "HDFCLIFE", instrumentKey: "NSE_EQ|INE795G01014", name: "HDFC Life Insurance" },
  { symbol: "BANKBARODA", instrumentKey: "NSE_EQ|INE028A01039", name: "Bank of Baroda" },
  { symbol: "PNB", instrumentKey: "NSE_EQ|INE160A01022", name: "Punjab National Bank" },
  { symbol: "VEDL", instrumentKey: "NSE_EQ|INE205A01025", name: "Vedanta" },
  { symbol: "HINDALCO", instrumentKey: "NSE_EQ|INE038A01020", name: "Hindalco Industries" },
  { symbol: "TRENT", instrumentKey: "NSE_EQ|INE849A01020", name: "Trent" },
  { symbol: "ZOMATO", instrumentKey: "NSE_EQ|INE758T01015", name: "Zomato" },
  { symbol: "CANBK", instrumentKey: "NSE_EQ|INE476A01022", name: "Canara Bank" },
  { symbol: "IDFCFIRSTB", instrumentKey: "NSE_EQ|INE092T01019", name: "IDFC First Bank" },
];
